# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: VM-AWS

steps:

# SCAN de API pertore utilizando comando WI para executar o scan e forticlient para submeter os scans ao Sosftware Security Center
- task: CmdLine@2
  inputs:
    script: |
      wi -u https://petstore.swagger.io/v2/swagger.json -api Swagger -n "petstore" -CrawlCoverage Default -ps 1044 -r "Aggregate;Executive Summary;Developer Reference" -y Standard -f "C:\webinspect\petstore\report.pdf" -gp -ep ""C:\webinspect\petstore\output.fpr" -v
      fortifyclient -url https://34.193.130.215:8443/ssc -authtoken 8a88efe1-c17e-421c-9ffc-d6e8a08737ec uploadFPR -file "C:\webinspect\petstore\output.fpr" -project "petstore" -version petstore-azure
      